# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/adeswand/ameyarepo/workspace/fpga/proj/base_zynq/base_zynq.srcs/sources_1/bd/base_zynq/ip/base_zynq_rst_ps7_0_50M_0/base_zynq_rst_ps7_0_50M_0.xci
# IP: The module: 'base_zynq_rst_ps7_0_50M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/adeswand/ameyarepo/workspace/fpga/proj/base_zynq/base_zynq.srcs/sources_1/bd/base_zynq/ip/base_zynq_rst_ps7_0_50M_0/base_zynq_rst_ps7_0_50M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'base_zynq_rst_ps7_0_50M_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/adeswand/ameyarepo/workspace/fpga/proj/base_zynq/base_zynq.srcs/sources_1/bd/base_zynq/ip/base_zynq_rst_ps7_0_50M_0/base_zynq_rst_ps7_0_50M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'base_zynq_rst_ps7_0_50M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/adeswand/ameyarepo/workspace/fpga/proj/base_zynq/base_zynq.srcs/sources_1/bd/base_zynq/ip/base_zynq_rst_ps7_0_50M_0/base_zynq_rst_ps7_0_50M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'base_zynq_rst_ps7_0_50M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /home/adeswand/ameyarepo/workspace/fpga/proj/base_zynq/base_zynq.srcs/sources_1/bd/base_zynq/ip/base_zynq_rst_ps7_0_50M_0/base_zynq_rst_ps7_0_50M_0.xci
# IP: The module: 'base_zynq_rst_ps7_0_50M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/adeswand/ameyarepo/workspace/fpga/proj/base_zynq/base_zynq.srcs/sources_1/bd/base_zynq/ip/base_zynq_rst_ps7_0_50M_0/base_zynq_rst_ps7_0_50M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'base_zynq_rst_ps7_0_50M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/adeswand/ameyarepo/workspace/fpga/proj/base_zynq/base_zynq.srcs/sources_1/bd/base_zynq/ip/base_zynq_rst_ps7_0_50M_0/base_zynq_rst_ps7_0_50M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'base_zynq_rst_ps7_0_50M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/adeswand/ameyarepo/workspace/fpga/proj/base_zynq/base_zynq.srcs/sources_1/bd/base_zynq/ip/base_zynq_rst_ps7_0_50M_0/base_zynq_rst_ps7_0_50M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'base_zynq_rst_ps7_0_50M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
